---
namespace: ${namespace}
sys_path: ./blueprints
stacker_bucket: ${namespace}-stacker-${stacker_bucket_region}
tags: &tags
  owner: arodriguezfebres@gmail.com
pre_build:
  - path: stacker.hooks.aws_lambda.upload_lambda_functions
    required: true
    enabled: true
    data_key: lambda
    args:
      FetchTime:
        path: ./lambdas/dir_fetch_time/
        include:
          - '*.py'
          - '*.txt'
        exclude:
          - '*.pyc'
          - test/
stacks:
  - name : FetchTime
    class_path: lambda.Function
    description: Function returns current time.
    tags:
      <<: *tags
    variables:
      InlineCode: <stacker -DUMP placeholder> # If pre_build hook enabled, inline code will be overwritten on deploy
      Description: >
        Function returns current time.
      MemorySize: 512
      ReservedConcurrentExecutions: 15
      Handler: func_fetch_time.main
      Runtime: python3.7
  - name : FetchTimeAPIResources
    class_path: apigateway.TemplateBuilder
    description: API Gateway resources.
    tags:
      <<: *tags
    variables:
      InvokeLambda: ${namespace}-FetchTime-FetchTimeArn
      InvokeLambdaRole: ${namespace}-FetchTime-FetchTimeRoleArn
      Region: ${stacker_bucket_region}
      Name: FetchTime