---
namespace: ${namespace}
sys_path: ./blueprints
tags: &tags
  owner: arodriguezfebres@gmail.com
stacks:
  - name: s3-stacker-bucket
    class_path: s3_stacker_bucket.TemplateBuilder # ./blueprints/s3_stacker_bucket.py
    description: Template to build S3 stacker bucket
    tags:
      <<: *tags
    variables:
      BucketName: ${namespace}-stacker-${stacker_bucket_region}